# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd34a3410ab88dbeaf8e2f1849cf3fb864a61e4d0644a77aea4ec20dc4904b5023a0d3801256280f929fa279ef17bf1734b43e2cbf09052848f2029e31eb819f

test:
  secret_key_base: 1664c59a968b8267053dfbd167022e2b79e78aed991ed66552f81dc092d2b01204334b09f3cd5f99f0d4c7afb227a1d7b62c8a445ddb43951bf8fd84e137ac82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
