# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c95594ebb2e515458072c3c155d18e3de76fbbabd5a9d3a7048d01904c1c0bbd0e79b82abfeeebe23d7f6ebe5ff8a119355ccb88b9bc40b4856f128602992cef

test:
  secret_key_base: 6255f69a2a6f7ed4ebb35213c9de18678fb4fe1af7fb283ee44d91f4ab91d3c24f4d74692afa9b76869e6f5515e9f7b3738e535bcfb588a0acdde5b5298167e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
